export type ComponentCategory =
  'foundation' | 'layout' | 'form' | 'navigation' | 'data-display' | 'feedback' | 'overlay'

export interface ComponentSpec {
  name: string
  category: ComponentCategory
  purpose: string
  useWhen: string
  avoidWhen: string
  variants: string[]
  accessibility: string
}

export const componentSpecs: ComponentSpec[] = [
  {
    name: 'Button',
    category: 'foundation',
    purpose: '触发明确动作',
    useWhen: '提交、创建、保存或执行命令',
    avoidWhen: '目标是导航；此时使用链接',
    variants: ['primary', 'secondary', 'ghost', 'danger', 'warning', 'loading'],
    accessibility: '使用原生 button；异步状态自动 disabled 与 aria-busy',
  },
  {
    name: 'IconButton',
    category: 'foundation',
    purpose: '在紧凑工具栏中触发动作',
    useWhen: '图标含义稳定且空间受限',
    avoidWhen: '新用户无法仅凭图标理解动作',
    variants: ['sm', 'md', 'lg'],
    accessibility: '类型层强制 aria-label；图标本身隐藏于辅助技术',
  },
  {
    name: 'Surface',
    category: 'foundation',
    purpose: '表达基础表面层级',
    useWhen: '需要默认、次级或浮起表面',
    avoidWhen: '仅为了包一层圆角容器',
    variants: ['default', 'subtle', 'raised'],
    accessibility: '不改变语义；由调用方选择正确 HTML 结构',
  },
  {
    name: 'Card',
    category: 'data-display',
    purpose: '组合标题、内容和动作',
    useWhen: '内容可作为独立信息单元理解',
    avoidWhen: '页面结构主要依赖大量同质卡片',
    variants: ['header', 'content', 'footer'],
    accessibility: '卡片本身不可假装按钮；交互使用内部按钮或链接',
  },
  {
    name: 'Panel',
    category: 'data-display',
    purpose: '构建工作台设置面板',
    useWhen: '区域具有标题、说明、动作和可选页脚',
    avoidWhen: '只需要简单视觉分组',
    variants: ['header', 'content', 'footer'],
    accessibility: '输出 section 与 h2，保持页面标题层级连续',
  },
  {
    name: 'Container',
    category: 'layout',
    purpose: '约束页面内容宽度与边距',
    useWhen: '页面需要统一阅读或工作宽度',
    avoidWhen: '画布、时间线等必须全宽的工作区',
    variants: ['sm', 'md', 'lg', 'full'],
    accessibility: '不改变内容语义',
  },
  {
    name: 'Stack',
    category: 'layout',
    purpose: '建立垂直节奏',
    useWhen: '同组元素垂直排列',
    avoidWhen: '需要复杂二维网格',
    variants: ['gap 4–48'],
    accessibility: '不改变内容语义',
  },
  {
    name: 'Inline',
    category: 'layout',
    purpose: '建立行内动作或元数据布局',
    useWhen: '控件和短文本需要水平排列',
    avoidWhen: '长文本需要稳定阅读宽度',
    variants: ['wrap', 'nowrap', 'align', 'justify'],
    accessibility: 'DOM 顺序必须与视觉顺序一致',
  },
  {
    name: 'Grid',
    category: 'layout',
    purpose: '响应式排列同类项目',
    useWhen: '卡片、缩略图或表单列需要自适应',
    avoidWhen: '项目具有强制顺序或不同语义层级',
    variants: ['minColumnWidth', 'gap'],
    accessibility: '不使用 CSS 排序改变阅读顺序',
  },
  {
    name: 'SplitPane',
    category: 'layout',
    purpose: '构建侧栏加主工作区',
    useWhen: '导航/属性面板与主内容需要长期并列',
    avoidWhen: '次级内容只在偶尔使用时出现',
    variants: ['start', 'end'],
    accessibility: '窄屏回落为单列，避免不可达的横向区域',
  },
  {
    name: 'ScrollArea',
    category: 'layout',
    purpose: '提供可聚焦的受控滚动区',
    useWhen: '面板内部必须独立滚动',
    avoidWhen: '页面主滚动已能完成任务',
    variants: ['maxHeight'],
    accessibility: '滚动容器可键盘聚焦并显示焦点',
  },
  {
    name: 'Divider',
    category: 'layout',
    purpose: '分隔相邻内容组',
    useWhen: '仅靠间距不足以表达分组',
    avoidWhen: '页面已经有足够的层级和留白',
    variants: ['horizontal', 'vertical'],
    accessibility: '使用 hr 与 aria-orientation',
  },
  {
    name: 'TextField',
    category: 'form',
    purpose: '输入单行文本',
    useWhen: '名称、路径、参数或短值输入',
    avoidWhen: '多行内容或离散选项',
    variants: ['helper', 'error', 'required', 'readOnly'],
    accessibility: '可见 label；错误通过 aria-describedby 与 aria-invalid 关联',
  },
  {
    name: 'TextArea',
    category: 'form',
    purpose: '输入多行内容',
    useWhen: '提示词、说明、模板或长文本',
    avoidWhen: '结构化选项可减少输入错误',
    variants: ['helper', 'error', 'required'],
    accessibility: '可见 label；允许用户调整高度',
  },
  {
    name: 'Checkbox',
    category: 'form',
    purpose: '选择独立布尔项或多选项',
    useWhen: '多个选项可同时成立',
    avoidWhen: '二选一即时设置更适合 Switch',
    variants: ['primary', 'danger', 'indeterminate'],
    accessibility: '使用原生 checkbox；标签与说明扩大点击区域',
  },
  {
    name: 'Switch',
    category: 'form',
    purpose: '即时开启或关闭设置',
    useWhen: '切换立即生效且无需提交',
    avoidWhen: '属于表单提交的一部分',
    variants: ['label start', 'label end'],
    accessibility: '原生 checkbox + role=switch；状态不只依赖颜色',
  },
  {
    name: 'RadioGroup',
    category: 'form',
    purpose: '从少量互斥选项中选择一个',
    useWhen: '2–5 个选项需要同时可见比较',
    avoidWhen: '选项很多；使用 SelectField',
    variants: ['vertical', 'horizontal'],
    accessibility: 'fieldset/legend 分组；同名原生 radio',
  },
  {
    name: 'SegmentedControl',
    category: 'form',
    purpose: '在紧凑空间切换少量互斥模式',
    useWhen: '2–4 个短标签、切换影响当前视图',
    avoidWhen: '用于页面主导航或选项标签过长',
    variants: ['sm', 'md'],
    accessibility: 'radiogroup/radio 语义与 aria-checked',
  },
  {
    name: 'ColorSchemeSwitcher',
    category: 'form',
    purpose: '在皮肤（配色方案）间切换整体视觉',
    useWhen: '顶栏、设置或设计系统需要在注册表驱动的全部配色预设间切换',
    avoidWhen: '只需在深浅主题间切换；此时使用主题切换',
    variants: ['sm', 'md'],
    accessibility: '基于 SegmentedControl 的 radiogroup/radio；色板仅装饰，文字标签提供可读名称',
  },
  {
    name: 'ColorPresetGrid',
    category: 'form',
    purpose: '以卡片网格形式选择配色预设',
    useWhen: '设置页「主题」区块需要展示渐变预览、名称与选中状态',
    avoidWhen: '空间极小或只需要 2–3 个紧凑选项；此时使用 ColorSchemeSwitcher',
    variants: ['columns 2/3/4'],
    accessibility: 'radiogroup/radio 语义；每张卡片用 aria-checked 标示选中，渐变仅装饰',
  },
  {
    name: 'SelectField',
    category: 'form',
    purpose: '从列表中选择单个值',
    useWhen: '选项较多且无需复杂动作',
    avoidWhen: '选项需要拖拽、编辑或多级交互',
    variants: ['helper', 'error', 'disabled'],
    accessibility: '优先使用原生 select，保留键盘与系统行为',
  },
  {
    name: 'SearchField',
    category: 'form',
    purpose: '过滤当前可见集合',
    useWhen: '任务、标签、设置或素材列表可搜索',
    avoidWhen: '搜索会跳转到全新信息架构',
    variants: ['clearable', 'sm', 'md', 'lg'],
    accessibility: '使用 search 类型与可访问标签',
  },
  {
    name: 'Fieldset',
    category: 'form',
    purpose: '组织相关表单设置',
    useWhen: '多个字段共同描述一个设置组',
    avoidWhen: '只有一个字段',
    variants: ['description', 'actions'],
    accessibility: '使用 fieldset/legend 建立组语义',
  },
  {
    name: 'Stepper',
    category: 'form',
    purpose: '小步调整受限数字',
    useWhen: '数量、并发或等级范围较小',
    avoidWhen: '精确大范围数字；使用 number input',
    variants: ['min', 'max', 'step'],
    accessibility: '增减按钮有完整名称，output 使用 aria-live',
  },
  {
    name: 'Badge',
    category: 'feedback',
    purpose: '显示短状态或分类',
    useWhen: '状态可用 1–4 个字表达',
    avoidWhen: '承载动作或长说明',
    variants: ['neutral', 'info', 'success', 'warning', 'danger'],
    accessibility: '文本必须能脱离颜色独立理解',
  },
  {
    name: 'StatusIndicator',
    category: 'feedback',
    purpose: '显示运行状态与短标签',
    useWhen: '在线、运行中、已完成或失败状态',
    avoidWhen: '错误需要恢复操作；使用 Alert',
    variants: ['neutral', 'info', 'success', 'warning', 'danger'],
    accessibility: '圆点是装饰，文字提供完整状态',
  },
  {
    name: 'Alert',
    category: 'feedback',
    purpose: '提供区域级信息或恢复指导',
    useWhen: '需要说明原因、影响和下一步',
    avoidWhen: '短暂成功反馈；使用 ToastMessage',
    variants: ['info', 'success', 'warning', 'danger'],
    accessibility: '错误使用 alert，非阻断信息使用 status',
  },
  {
    name: 'ToastMessage',
    category: 'feedback',
    purpose: '反馈刚完成的全局动作',
    useWhen: '结果无需用户立即处理',
    avoidWhen: '错误会阻断当前任务',
    variants: ['info', 'success', 'warning', 'danger'],
    accessibility: '使用 aria-live，不抢焦点；可选明确关闭按钮',
  },
  {
    name: 'Spinner',
    category: 'feedback',
    purpose: '指示短时不确定等待',
    useWhen: '局部操作预计等待 0.3–1 秒',
    avoidWhen: '内容结构已知；优先 Skeleton',
    variants: ['sm', 'md', 'lg'],
    accessibility: 'role=status 与可配置加载文案',
  },
  {
    name: 'Progress',
    category: 'feedback',
    purpose: '显示确定或不确定进度',
    useWhen: '批处理、导出、上传或生成流程',
    avoidWhen: '无法估计且等待极短',
    variants: ['determinate', 'indeterminate', 'tones'],
    accessibility: '完整 progressbar 数值属性',
  },
  {
    name: 'Skeleton',
    category: 'feedback',
    purpose: '为将出现的内容保留空间',
    useWhen: '内容结构已知且等待超过 1 秒',
    avoidWhen: '动作结果只需一个局部 Spinner',
    variants: ['arbitrary shape'],
    accessibility: '包含屏幕阅读器状态文本；减少动态时停止脉冲',
  },
  {
    name: 'EmptyState',
    category: 'feedback',
    purpose: '解释空集合并给出下一步',
    useWhen: '列表或工作区还没有内容',
    avoidWhen: '加载中或加载失败',
    variants: ['icon', 'description', 'action'],
    accessibility: '标题、说明和行动顺序清晰',
  },
  {
    name: 'ErrorState',
    category: 'feedback',
    purpose: '解释失败并提供恢复路径',
    useWhen: '整个区域无法继续展示',
    avoidWhen: '单字段错误或短暂 Toast 足够',
    variants: ['retry', 'details'],
    accessibility: '可恢复动作明确；技术详情可读且不覆盖主说明',
  },
  {
    name: 'Kbd',
    category: 'feedback',
    purpose: '展示键盘快捷键',
    useWhen: '工具提示、菜单或帮助文档',
    avoidWhen: '快捷键并未实现',
    variants: [],
    accessibility: '使用 kbd 语义，不把快捷键作为唯一操作入口',
  },
  {
    name: 'Tabs',
    category: 'navigation',
    purpose: '切换同一上下文中的并列内容',
    useWhen: '内容层级相同且无需 URL 历史',
    avoidWhen: '顶层页面导航',
    variants: ['sm', 'md', 'stretch'],
    accessibility: 'tablist/tab；箭头键切换与 roving tabindex',
  },
  {
    name: 'Toolbar',
    category: 'navigation',
    purpose: '组合一组相关命令',
    useWhen: '画布、列表或编辑器的高频动作',
    avoidWhen: '动作语义互不相关',
    variants: [],
    accessibility: 'role=toolbar 与明确 aria-label',
  },
  {
    name: 'PageHeader',
    category: 'navigation',
    purpose: '建立页面标题、说明和主行动',
    useWhen: '每个独立页面或工作区入口',
    avoidWhen: '弹窗和局部面板',
    variants: ['breadcrumbs', 'eyebrow', 'actions'],
    accessibility: '输出唯一 h1；窄屏动作自动换行',
  },
  {
    name: 'SectionHeader',
    category: 'navigation',
    purpose: '标识页面内区域',
    useWhen: '区域具有独立标题和动作',
    avoidWhen: '视觉分组不需要新标题层级',
    variants: ['description', 'actions'],
    accessibility: '输出 h2，调用方应保持层级连续',
  },
  {
    name: 'Breadcrumbs',
    category: 'navigation',
    purpose: '显示三级以上层级路径',
    useWhen: '用户需要返回上级集合',
    avoidWhen: '只有一级或二级导航',
    variants: ['link', 'button', 'current'],
    accessibility: 'nav + ol；当前位置 aria-current=page',
  },
  {
    name: 'NavList',
    category: 'navigation',
    purpose: '侧栏内切换主要或次要目的地',
    useWhen: '设置、素材库或管理中心',
    avoidWhen: '内容切换更适合 Tabs',
    variants: ['icon', 'badge', 'disabled'],
    accessibility: 'nav 有名称；当前位置使用 aria-current',
  },
  {
    name: 'ListRow',
    category: 'data-display',
    purpose: '展示可扫描的列表项目',
    useWhen: '标签页、任务、预设和历史记录；紧凑侧栏使用 divided 细线分隔，默认、悬停、选中与拖拽状态均不叠加行背景',
    avoidWhen: '内容以视觉缩略图为主',
    variants: ['leading', 'meta', 'actions', 'selected', 'interactive', 'divided'],
    accessibility:
      '交互行使用 interactive 提供的原生按钮；当前位置使用 aria-current，批量选择使用 aria-pressed；divided 选中态同时使用字重与颜色',
  },
  {
    name: 'Stat',
    category: 'data-display',
    purpose: '显示一个指标及补充信息',
    useWhen: '总数、成功、失败、耗时',
    avoidWhen: '指标没有决策价值',
    variants: ['trend'],
    accessibility: '数字使用 tabular figures；标签始终可见',
  },
  {
    name: 'KeyValue',
    category: 'data-display',
    purpose: '展示参数和只读元数据',
    useWhen: '详情、导出记录、设置摘要',
    avoidWhen: '值需要编辑；使用表单字段',
    variants: [],
    accessibility: '基于 dt/dd 的键值语义',
  },
  {
    name: 'Thumbnail',
    category: 'data-display',
    purpose: '展示有固定比例的图像预览',
    useWhen: '任务卡、素材库和结果列表',
    avoidWhen: '图像是主浏览内容；使用画廊或 Lightbox',
    variants: ['ratio', 'selected'],
    accessibility: '强制 alt；声明比例避免布局跳动',
  },
  {
    name: 'AspectRatio',
    category: 'data-display',
    purpose: '为媒体预留稳定比例',
    useWhen: '图片、视频或画布预览',
    avoidWhen: '内容高度由文本自然决定',
    variants: ['ratio'],
    accessibility: '不改变内部媒体语义',
  },
  {
    name: 'Disclosure',
    category: 'data-display',
    purpose: '渐进展示次级内容',
    useWhen: '帮助、进阶设置和长结果细节',
    avoidWhen: '关键内容必须默认可见',
    variants: ['open', 'closed'],
    accessibility: '使用原生 details/summary',
  },
  {
    name: 'CodeBlock',
    category: 'data-display',
    purpose: '展示提示词模板、JSON 或代码',
    useWhen: '内容需要保留空白和等宽对齐',
    avoidWhen: '普通说明文字',
    variants: ['language'],
    accessibility: 'pre/code 语义；内容区域可滚动',
  },
  {
    name: 'Table',
    category: 'data-display',
    purpose: '展示列间需要比较的数据',
    useWhen: '历史记录、导出结果和结构化参数',
    avoidWhen: '移动端只需单项浏览；改用 ListRow',
    variants: ['header', 'body', 'row', 'cell'],
    accessibility: '保留原生 table 结构；容器可键盘滚动',
  },
  {
    name: 'Dialog',
    category: 'overlay',
    purpose: '保护需要集中注意的短任务',
    useWhen: '确认、短表单或高风险操作',
    avoidWhen: '主流程、多步骤或无需打断的内容',
    variants: ['sm', 'md', 'lg', 'xl'],
    accessibility: '焦点锁定、Escape 关闭、关闭后归还焦点、aria-modal',
  },
  {
    name: 'DialogWorkspace',
    category: 'overlay',
    purpose: '统一复杂弹窗内部工作区结构',
    useWhen: '弹窗内含列表、表单、状态栏等多个并列 pane',
    avoidWhen: '只有短表单或确认内容；直接使用 Dialog content',
    variants: ['single', 'split', 'triple'],
    accessibility: '不制造新的页面层级；pane 顺序即阅读和键盘顺序',
  },
  {
    name: 'DialogPane',
    category: 'overlay',
    purpose: '定义复杂弹窗内的侧栏、内容区和画布区',
    useWhen: 'DialogWorkspace 需要分隔滚动、边界和表面层级',
    avoidWhen: '仅为了套一层卡片或背景',
    variants: ['sidebar', 'content', 'canvas', 'scroll'],
    accessibility: '默认保留原生 section/aside/div 语义并避免不可达嵌套滚动',
  },
  {
    name: 'Drawer',
    category: 'overlay',
    purpose: '展示保留上下文的次级工作区',
    useWhen: '属性、素材库、设置或窄屏侧栏',
    avoidWhen: '高风险确认；使用 Dialog',
    variants: ['left', 'right', 'bottom', 'sm', 'md', 'lg'],
    accessibility: '继承 Dialog 的焦点管理；窄屏保持安全区',
  },
  {
    name: 'Tooltip',
    category: 'overlay',
    purpose: '解释图标或陌生控件',
    useWhen: '标签无法常驻且信息非关键',
    avoidWhen: '表单帮助、错误或触屏唯一入口',
    variants: ['top', 'right', 'bottom', 'left'],
    accessibility: '触发器通过 aria-describedby 关联；键盘聚焦可显示',
  },
  {
    name: 'Popover',
    category: 'overlay',
    purpose: '承载与触发器相关的轻量内容',
    useWhen: '筛选、颜色、尺寸或简短设置',
    avoidWhen: '复杂表单或需要保护焦点',
    variants: ['arrow'],
    accessibility: '提供明确 label；定位和打开状态由调用方管理',
  },
  {
    name: 'Menu',
    category: 'overlay',
    purpose: '展示一组离散命令',
    useWhen: '右键菜单、更多操作和下拉命令',
    avoidWhen: '用户需要比较或填写选项',
    variants: ['item', 'danger', 'separator', 'shortcut'],
    accessibility: 'menu/menuitem；方向键、Home、End 可移动焦点',
  },
]

export type LegacyDecision = 'migrate' | 'compose' | 'retain'

export interface LegacyComponentCoverage {
  module: string
  responsibility: string
  decision: LegacyDecision
  targets: string[]
}

export const legacyComponentCoverage: LegacyComponentCoverage[] = [
  {
    module: 'src/components/AgentBatchPlannerModal.tsx',
    responsibility: 'Agent 批量规划表单弹窗',
    decision: 'compose',
    targets: ['Dialog', 'Fieldset', 'TextField', 'SelectField', 'Button', 'Alert'],
  },
  {
    module: 'src/components/AgentBatchQueueRunner.tsx',
    responsibility: '后台批量执行协调器',
    decision: 'retain',
    targets: ['Progress', 'ToastMessage', 'StatusIndicator'],
  },
  {
    module: 'src/components/AgentImageGrid.tsx',
    responsibility: 'Agent 图片结果网格与预览条',
    decision: 'compose',
    targets: ['Grid', 'Thumbnail', 'AspectRatio', 'EmptyState'],
  },
  {
    module: 'src/components/AgentWorkspace.tsx',
    responsibility: 'Agent 对话、工具状态与结果工作区',
    decision: 'retain',
    targets: ['SplitPane', 'Toolbar', 'StatusIndicator', 'Alert', 'Progress', 'Thumbnail'],
  },
  {
    module: 'src/components/AppPageRail.tsx',
    responsibility: '桌面端低存在感页面翻页导航',
    decision: 'retain',
    targets: [],
  },
  { module: 'src/components/Checkbox.tsx', responsibility: '全局复选框', decision: 'migrate', targets: ['Checkbox'] },
  {
    module: 'src/components/ConfirmDialog.tsx',
    responsibility: '全局确认和破坏性操作对话框',
    decision: 'compose',
    targets: ['Dialog', 'Button', 'Checkbox', 'Alert'],
  },
  {
    module: 'src/components/DetailModal.tsx',
    responsibility: '任务详情与参数弹窗',
    decision: 'retain',
    targets: ['Dialog', 'Tabs', 'KeyValue', 'Thumbnail', 'Toolbar'],
  },
  {
    module: 'src/components/ErrorBoundary.tsx',
    responsibility: '应用级崩溃兜底',
    decision: 'compose',
    targets: ['ErrorState', 'Button'],
  },
  {
    module: 'src/components/FavoriteCollections.tsx',
    responsibility: '收藏夹视图、卡片和管理弹窗集合',
    decision: 'retain',
    targets: ['Grid', 'Card', 'Thumbnail', 'Dialog', 'SearchField', 'Menu'],
  },
  {
    module: 'src/components/GalleryImageTile.tsx',
    responsibility: '画廊图片平铺单元与选择交互',
    decision: 'compose',
    targets: ['Thumbnail', 'AspectRatio', 'StatusIndicator'],
  },
  {
    module: 'src/components/Header.tsx',
    responsibility: '全局顶栏、模式导航和生成统计',
    decision: 'retain',
    targets: ['Toolbar', 'Tabs', 'Stat', 'IconButton', 'Tooltip'],
  },
  {
    module: 'src/components/HelpModal.tsx',
    responsibility: '模式化帮助文档弹窗',
    decision: 'compose',
    targets: ['Dialog', 'Tabs', 'Disclosure', 'CodeBlock'],
  },
  {
    module: 'src/components/HoverImagePreview.tsx',
    responsibility: '悬停图片预览浮层',
    decision: 'retain',
    targets: ['Popover', 'Thumbnail'],
  },
  {
    module: 'src/components/ImageContextMenu.tsx',
    responsibility: '图片右键命令菜单',
    decision: 'compose',
    targets: ['Menu', 'Kbd'],
  },
  {
    module: 'src/components/InputBar.tsx',
    responsibility: '主提示词输入、参数和批量动作工作台',
    decision: 'retain',
    targets: ['TextArea', 'Toolbar', 'Button', 'IconButton', 'SelectField', 'Stepper', 'Tooltip', 'Popover'],
  },
  {
    module: 'src/components/LargeModalToggle.tsx',
    responsibility: '弹窗默认尺寸与 80% 大弹窗模式切换',
    decision: 'compose',
    targets: ['Button', 'Dialog'],
  },
  {
    module: 'src/components/LegacyDataImportModal.tsx',
    responsibility: '旧版数据导入（目录复制 + 跨模式数据文件迁移）',
    decision: 'compose',
    targets: ['Dialog', 'ListRow', 'Button', 'Checkbox'],
  },
  {
    module: 'src/components/Lightbox.tsx',
    responsibility: '全屏图片查看和导航',
    decision: 'retain',
    targets: ['Dialog', 'Toolbar', 'IconButton', 'StatusIndicator'],
  },
  {
    module: 'src/components/ModelSwitcher.tsx',
    responsibility: '输入框内的一键模型切换器：生图模型按 API 配置切换、文本模型下拉/手动输入',
    decision: 'retain',
    targets: ['IconButton', 'Spinner'],
  },
  {
    module: 'src/components/PostprocessSettingsModal.tsx',
    responsibility: '后处理编排面板：启用范围、媒体与尺寸、输出与命名、水印归属汇总（来源为项目树参数）与产出预览',
    decision: 'compose',
    targets: [
      'Dialog',
      'SectionHeader',
      'Checkbox',
      'SegmentedControl',
      'TextField',
      'Switch',
      'Button',
      'IconButton',
      'Alert',
      'EmptyState',
      'Surface',
    ],
  },
  {
    module: 'src/components/MarkdownRenderer.tsx',
    responsibility: 'Markdown 和流式内容渲染',
    decision: 'retain',
    targets: ['CodeBlock', 'Table'],
  },
  {
    module: 'src/components/MaskEditorModal.tsx',
    responsibility: '遮罩绘制编辑器',
    decision: 'retain',
    targets: ['Dialog', 'Toolbar', 'Button', 'Progress'],
  },
  {
    module: 'src/components/PromptInputDialog.tsx',
    responsibility: '提示词输入弹窗',
    decision: 'compose',
    targets: ['Dialog', 'TextArea', 'Button'],
  },
  {
    module: 'src/components/PromptVariableEditor.tsx',
    responsibility: '提示词变量编辑器（富文本 contentEditable）',
    decision: 'retain',
    targets: [],
  },
  {
    module: 'src/components/RandomPromptModal.tsx',
    responsibility: '随机词库管理弹窗',
    decision: 'retain',
    targets: ['Dialog', 'Tabs', 'SearchField', 'ListRow', 'EmptyState'],
  },
  {
    module: 'src/components/ScheduleModal.tsx',
    responsibility: '日程表、任务单元和预览弹窗',
    decision: 'retain',
    targets: ['Dialog', 'Tabs', 'Toolbar', 'ListRow', 'Popover'],
  },
  {
    module: 'src/components/ScheduleRunner.tsx',
    responsibility: '日程执行协调器',
    decision: 'retain',
    targets: ['ToastMessage', 'StatusIndicator', 'Progress'],
  },
  {
    module: 'src/components/Select.tsx',
    responsibility: '支持动作和拖拽排序的高级选择器',
    decision: 'retain',
    targets: ['SelectField', 'Popover', 'Menu'],
  },
  {
    module: 'src/components/SettingsModal.tsx',
    responsibility: '全局设置和 API 配置弹窗',
    decision: 'retain',
    targets: ['Dialog', 'Tabs', 'Fieldset', 'TextField', 'SelectField', 'Switch', 'Alert'],
  },
  {
    module: 'src/components/SizePickerModal.tsx',
    responsibility: '输出尺寸选择弹窗',
    decision: 'compose',
    targets: ['Dialog', 'Grid', 'SegmentedControl', 'Button'],
  },
  {
    module: 'src/components/SopBatchDetailModal.tsx',
    responsibility: 'SOP 批次结果详情弹窗',
    decision: 'compose',
    targets: ['Dialog', 'Grid', 'Thumbnail', 'StatusIndicator', 'Progress'],
  },
  {
    module: 'src/components/SopBatchTaskCard.tsx',
    responsibility: 'SOP 批量任务卡',
    decision: 'compose',
    targets: ['Card', 'Thumbnail', 'StatusIndicator', 'Toolbar'],
  },
  {
    module: 'src/components/TaskCard.tsx',
    responsibility: '图片生成任务卡及动作',
    decision: 'retain',
    targets: ['Card', 'Thumbnail', 'StatusIndicator', 'Toolbar', 'Menu'],
  },
  {
    module: 'src/components/TaskPostprocessModal.tsx',
    responsibility: '任务后处理产出清单弹层，可逐条打开所在文件夹',
    decision: 'compose',
    targets: ['Dialog', 'ListRow', 'IconButton'],
  },
  {
    module: 'src/components/TaskParamSummary.tsx',
    responsibility: '任务参数摘要标签',
    decision: 'compose',
    targets: ['StatusIndicator'],
  },
  {
    module: 'src/components/Toast.tsx',
    responsibility: '全局短暂反馈',
    decision: 'migrate',
    targets: ['ToastMessage'],
  },
  {
    module: 'src/components/UpdateReleaseNotesModal.tsx',
    responsibility: '版本更新说明弹窗',
    decision: 'compose',
    targets: ['Dialog', 'Disclosure', 'Button'],
  },
  {
    module: 'src/components/ViewportTooltip.tsx',
    responsibility: '防溢出的视口级工具提示（复用 ds-tooltip 深色气泡视觉，配合统一 useTooltip）',
    decision: 'retain',
    targets: ['Tooltip'],
  },
  {
    module: 'src/components/paramDisplay.tsx',
    responsibility: '任务参数展示组件（DetailParamValue / ActualValueBadge），配合 ViewportTooltip 显示完整值',
    decision: 'retain',
    targets: ['Tooltip'],
  },
  {
    module: 'src/components/WordLibrarySidebar.tsx',
    responsibility: '可停靠词库侧栏',
    decision: 'retain',
    targets: ['SplitPane', 'Panel', 'SearchField', 'NavList'],
  },
  {
    module: 'src/components/WorkspaceTabBar.tsx',
    responsibility: '可停靠标签页侧栏、分组和右键菜单',
    decision: 'retain',
    targets: ['Panel', 'SearchField', 'ListRow', 'Menu', 'Toolbar'],
  },
  {
    module: 'src/components/WorkspaceTabManagerModal.tsx',
    responsibility: '标签页和分组管理弹窗',
    decision: 'retain',
    targets: ['Dialog', 'SearchField', 'ListRow', 'Menu', 'EmptyState'],
  },
  {
    module: 'src/features/assetLibrary/AssetCardMenu.tsx',
    responsibility: '素材卡片右键菜单（收藏、评分、参考图、下载、回收站）',
    decision: 'compose',
    targets: ['Menu', 'Tooltip'],
  },
  {
    module: 'src/features/assetLibrary/AssetTile.tsx',
    responsibility:
      '图片砖：图片/列表/分组三种展现方式共用的单张素材卡片（缩略图、hover、选择、查看器、右键菜单、快捷条）',
    decision: 'compose',
    targets: ['IconButton', 'Tooltip'],
  },
  {
    module: 'src/features/assetLibrary/AssetDetailPanel.tsx',
    responsibility: '素材详情（大图、评分、收藏、来源、项目、标签）',
    decision: 'compose',
    targets: ['IconButton', 'Tooltip', 'Badge'],
  },
  {
    module: 'src/features/assetLibrary/FilterControlStrip.tsx',
    responsibility: '工具栏筛选控件条：「+」菜单自主选择把哪些筛选参数（维度级）常驻工具栏，选值即筛选（持久化）',
    decision: 'compose',
    targets: ['IconButton', 'Menu'],
  },
  {
    module: 'src/features/assetLibrary/AssetFilterTabBar.tsx',
    responsibility:
      '顶部筛选标签栏（Eagle 式）：固定标签（常用筛选条件，持久化、可拖动排序）+ 临时标签（当前生效条件自动打开），点击应用/取消、可关闭',
    decision: 'compose',
    targets: ['IconButton'],
  },
  {
    module: 'src/features/assetLibrary/AssetGrid.tsx',
    responsibility: '素材瀑布流网格（缩略图懒加载与分页）',
    decision: 'compose',
    targets: ['EmptyState', 'Spinner', 'Thumbnail'],
  },
  {
    module: 'src/features/assetLibrary/AssetLibrarySidebar.tsx',
    responsibility: '素材库左侧导航（系统范围、智能文件夹、项目/标签树；筛选、右键菜单、拖放归档、宽度拖拽）',
    decision: 'compose',
    targets: ['NavList', 'IconButton', 'Tooltip', 'Menu'],
  },
  {
    module: 'src/features/assetLibrary/AssetLibraryToolbar.tsx',
    responsibility: '素材库搜索、筛选、排序与视角切换',
    decision: 'compose',
    targets: ['Toolbar', 'SearchField', 'Badge', 'Popover', 'Menu', 'SegmentedControl'],
  },
  {
    module: 'src/features/assetLibrary/AssetLibraryWorkspace.tsx',
    responsibility: '素材库三栏工作区容器',
    decision: 'compose',
    targets: ['Toolbar', 'NavList', 'SearchField', 'Badge', 'Popover', 'Menu', 'SegmentedControl'],
  },
  {
    module: 'src/features/assetLibrary/CollectionInfoModal.tsx',
    responsibility: '文件夹信息弹窗（素材数量、占用空间、子文件夹、时间）',
    decision: 'compose',
    targets: ['Dialog', 'KeyValue', 'Stat'],
  },
  {
    module: 'src/features/assetLibrary/AssetPickerModal.tsx',
    responsibility: '跨工作区素材选择器',
    decision: 'compose',
    targets: ['Dialog', 'SearchField', 'Grid', 'Thumbnail', 'EmptyState'],
  },
  {
    module: 'src/features/assetLibrary/AssetPurgeModal.tsx',
    responsibility: '永久删除确认（引用冲突预览与展示）',
    decision: 'compose',
    targets: ['Dialog', 'Button', 'Badge'],
  },
  {
    module: 'src/features/assetLibrary/AssetDuplicateModal.tsx',
    responsibility: '近似重复检测（感知哈希分组与一键回收站）',
    decision: 'compose',
    targets: ['Dialog', 'Button', 'Thumbnail'],
  },
  {
    module: 'src/features/assetLibrary/AssetViewer.tsx',
    responsibility: 'Eagle 式全屏查看器（缩放平移、左右浏览、类似图片、信息面板）',
    decision: 'compose',
    targets: ['IconButton', 'Tooltip', 'Badge', 'Thumbnail'],
  },
  {
    module: 'src/features/assetLibrary/AssetListView.tsx',
    responsibility: '素材列表视图（固定行高虚拟滚动、列头、行内元数据）',
    decision: 'compose',
    targets: ['EmptyState', 'Thumbnail'],
  },
  {
    module: 'src/features/assetLibrary/AssetParamBreakdown.tsx',
    responsibility: '素材参数解耦展示（任务级共享参数 + 本图专属参数：seed/实际差异/文件名）',
    decision: 'compose',
    targets: [],
  },
  {
    module: 'src/features/assetLibrary/AssetBatchView.tsx',
    responsibility:
      '分组视图（按批次/按任务）：旧画廊任务卡片形式（SopBatchTaskCard / TaskCard / OrphanBatchCard），卡片网格固定不随密度变化',
    decision: 'compose',
    targets: ['EmptyState', 'Card', 'Thumbnail', 'Button'],
  },
  {
    module: 'src/features/assetLibrary/SubfolderStrip.tsx',
    responsibility:
      '子文件夹区块（Eagle 式）：进入文件夹时顶部展示直接子文件夹封面卡片（封面 + 名称 + 素材数），点击进入',
    decision: 'compose',
    targets: ['Card', 'Thumbnail', 'Button'],
  },
  {
    module: 'src/features/assetLibrary/OrphanBatchCard.tsx',
    responsibility: '任务已删除的素材组卡片（封面 + 提示词摘要 + 打开查看器）',
    decision: 'compose',
    targets: ['Card', 'Thumbnail', 'Button'],
  },
  {
    module: 'src/features/assetLibrary/AssetQuickPreview.tsx',
    responsibility:
      'Eagle 式空格快速预览：按住空格显示选中素材大图（悬浮层），松开关闭；与全屏查看器（Enter/双击）独立',
    decision: 'compose',
    targets: ['Surface', 'Dialog'],
  },
  {
    module: 'src/components/DerivePolicyModal.tsx',
    responsibility: '一键衍生维度策略设置弹窗：8 个视觉维度 × 锁定/微调/大改三档勾选',
    decision: 'compose',
    targets: ['Dialog', 'SegmentedControl', 'Button'],
  },
  {
    module: 'src/features/composite/components/FloatingLayerToolbar.tsx',
    responsibility: '画布浮动图层工具条',
    decision: 'migrate',
    targets: ['Toolbar', 'Button', 'IconButton', 'Tooltip'],
  },
  {
    module: 'src/features/composite/components/FloatingLogoLibrary.tsx',
    responsibility: '浮动 Logo 素材库',
    decision: 'compose',
    targets: ['Panel', 'Grid', 'Thumbnail', 'IconButton', 'Tooltip'],
  },
  {
    module: 'src/features/composite/components/PresetCanvasEditor.tsx',
    responsibility: '预设画布编辑器',
    decision: 'retain',
    targets: ['Toolbar', 'AspectRatio', 'Popover', 'StatusIndicator'],
  },
  {
    module: 'src/features/composite/components/PresetLayerPanel.tsx',
    responsibility: '画布图层属性与顺序面板',
    decision: 'retain',
    targets: ['Panel', 'ListRow', 'Fieldset', 'Stepper', 'Menu'],
  },
  {
    module: 'src/features/composite/components/PresetManagementTab.tsx',
    responsibility: '水印预设工作区三栏装配（归属树 / 水印库 / 画布编辑）',
    decision: 'retain',
    targets: ['Tabs', 'Panel', 'ListRow', 'Menu', 'EmptyState'],
  },
  {
    module: 'src/features/composite/components/PresetProjectTree.tsx',
    responsibility:
      '水印归属树：项目树层级管理（新建/改名/删除/移动）+ 归属（拖入绑定、按渠道就地设置）。行上不挂分类 / 来源 / 状态标签，没绑定就一个节点一行',
    decision: 'retain',
    targets: ['Panel', 'ListRow', 'IconButton', 'Button', 'EmptyState'],
  },
  {
    module: 'src/features/composite/CompositeWorkspace.tsx',
    responsibility: '水印预设工作区装配（图层式水印编辑，编排已归后处理）',
    decision: 'retain',
    targets: ['SplitPane', 'Panel', 'Toolbar'],
  },
  {
    module: 'src/features/postprocess/PostprocessDistributionFields.tsx',
    responsibility: '分发配置表单（后处理面板与项目树节点参数弹窗共用同一份字段与措辞）',
    decision: 'compose',
    targets: ['Switch', 'TextField', 'SegmentedControl', 'Button', 'Alert'],
  },
  {
    module: 'src/features/projectTree/ProjectTreeWorkbench.tsx',
    responsibility: '统一项目树工作台（产品线→产品→方向 的增删改查与参数入口）',
    decision: 'compose',
    targets: ['Dialog', 'Button', 'TextField', 'SelectField'],
  },
  {
    module: 'src/features/projectTree/ProjectTreeTable.tsx',
    responsibility: '统一项目树表格（展平行 + 层级徽章 + 行内重命名）',
    decision: 'compose',
    targets: ['Table', 'IconButton', 'Button', 'TextField', 'EmptyState'],
  },
  {
    module: 'src/features/projectTree/ProjectNodeParamsDialog.tsx',
    responsibility: '单个树节点的后处理参数编辑（含继承状态与恢复继承）',
    decision: 'compose',
    targets: [
      'Dialog',
      'Button',
      'Checkbox',
      'SectionHeader',
      'SegmentedControl',
      'Surface',
      'Switch',
      'TextField',
      'Alert',
    ],
  },
  {
    module: 'src/features/requirementPrototype/QueueRunner.tsx',
    responsibility: '需求中心队列协调器',
    decision: 'retain',
    targets: ['Progress', 'ToastMessage', 'StatusIndicator'],
  },
  {
    module: 'src/features/strategy/adapters/GallerySopBatchModal.tsx',
    responsibility: '画廊 SOP 批量配置和执行弹窗',
    decision: 'retain',
    targets: ['Dialog', 'Fieldset', 'Thumbnail', 'Progress', 'Alert'],
  },
  {
    module: 'src/features/strategy/adapters/GallerySopManagementCenter.tsx',
    responsibility: '画廊 SOP 管理中心适配器',
    decision: 'retain',
    targets: ['PageHeader', 'SplitPane', 'Panel'],
  },
  {
    module: 'src/features/strategy/SopManagementCenter.tsx',
    responsibility: 'SOP 列表、搜索和管理中心',
    decision: 'retain',
    targets: ['PageHeader', 'SearchField', 'ListRow', 'Panel', 'EmptyState'],
  },
  {
    module: 'src/features/strategy/SopCoverImage.tsx',
    responsibility: 'SOP 封面缩略图',
    decision: 'compose',
    targets: ['Thumbnail', 'EmptyState'],
  },
  {
    module: 'src/features/strategy/SopImageStack.tsx',
    responsibility: 'SOP 列表生成结果叠层缩略图与 hover 大图预览',
    decision: 'compose',
    targets: ['Thumbnail', 'Popover'],
  },
  {
    module: 'src/features/strategy/SopCoverPickerDialog.tsx',
    responsibility: 'SOP 封面选择浮层',
    decision: 'compose',
    targets: ['Dialog', 'Thumbnail', 'EmptyState'],
  },
  {
    module: 'src/features/strategy/SopGenerateTab.tsx',
    responsibility: 'SOP 管理中心智能生成标签页（生成表单与状态/历史面板）',
    decision: 'compose',
    targets: ['Fieldset', 'TextArea', 'Progress', 'StatusIndicator', 'Alert'],
  },
  {
    module: 'src/features/strategy/SopLibraryTab.tsx',
    responsibility: 'SOP 管理中心 SOP 库标签页（分组侧栏、SOP 列表与参数编辑面板）',
    decision: 'compose',
    targets: ['Panel', 'SearchField', 'ListRow', 'EmptyState', 'TextArea'],
  },
  {
    module: 'src/features/strategy/SopMetaTab.tsx',
    responsibility: 'SOP 管理中心生成元指令标签页',
    decision: 'compose',
    targets: ['Panel', 'SearchField', 'ListRow', 'EmptyState', 'TextArea'],
  },
  {
    module: 'src/features/strategy/SopGenerationDetailOverlay.tsx',
    responsibility: 'SOP 智能生成记录详情浮层',
    decision: 'compose',
    targets: ['StatusIndicator', 'Panel', 'Alert'],
  },
  {
    module: 'src/features/strategy/SopPromptRunsDialog.tsx',
    responsibility: 'SOP 生成提示词集快照弹窗',
    decision: 'compose',
    targets: ['Dialog', 'EmptyState'],
  },
  {
    module: 'src/features/strategy/SopVersionHistoryDialog.tsx',
    responsibility: 'SOP 版本历史弹窗',
    decision: 'compose',
    targets: ['Dialog', 'EmptyState'],
  },
  {
    module: 'src/features/strategy/SeriesConsistencyControl.tsx',
    responsibility: '系列图一致性设置：维度固定/变化切换与固定值填写',
    decision: 'compose',
    targets: ['Popover'],
  },
  {
    module: 'src/features/strategy/SopAiRevisionPanel.tsx',
    responsibility: 'SOP AI 多轮修订对话与提案操作',
    decision: 'compose',
    targets: ['Toolbar', 'TextArea', 'StatusIndicator'],
  },
  {
    module: 'src/features/strategy/SopTextEditor.tsx',
    responsibility: 'SOP 正文格式化与查找编辑器',
    decision: 'compose',
    targets: ['Toolbar', 'TextArea', 'SearchField', 'StatusIndicator'],
  },
]

export interface InteractionPattern {
  id: string
  name: string
  appliesTo: string
  recipe: string[]
  rules: string[]
  relatedMaster: string
}

/** 跨两个以上场景重复出现的组合模式（对应 COMPONENTS.md 2.8）。 */
export const interactionPatterns: InteractionPattern[] = [
  {
    id: 'selectable-media-grid',
    name: '可选择媒体网格',
    appliesTo: '画廊任务网格、Agent 图片网格、收藏夹、SOP 批量结果',
    recipe: ['Grid', 'Thumbnail', 'AspectRatio', 'StatusIndicator', 'Toolbar', 'EmptyState', 'Skeleton'],
    rules: [
      '选择模型、框选、右键菜单遵循 MASTER 6.3/6.5，选中态使用 Selection Token',
      '超过 50 个复杂项必须虚拟化；选择状态存 id 集合，不依赖 DOM',
      '每个卡片四态：生成中（进度）、成功（图像）、失败（可重试占位）、已选中',
    ],
    relatedMaster: 'MASTER 6.3 / 6.5 / 6.6',
  },
  {
    id: 'tree-list-editor',
    name: '树 + 列表 + 编辑器工作台',
    appliesTo: '策略工作台、SOP 管理中心、预设管理、词库管理',
    recipe: ['SplitPane', 'NavList', 'ListRow', 'SearchField', 'Fieldset', 'TextField', 'Menu', 'EmptyState'],
    rules: [
      '树节点行内重命名：双击或菜单进入，Enter 提交、Escape 取消；编辑中禁用导航',
      '未保存的编辑器内容离开前必须确认或自动存草稿（Ctrl+S 见 MASTER 6.2）',
      '三栏在 1024px 以下折叠为两栏（导航转 Drawer），767px 以下单栏逐级下钻',
    ],
    relatedMaster: 'MASTER 4.4 / 6.2',
  },
  {
    id: 'queue-runner',
    name: '队列运行器',
    appliesTo: 'Agent 批量队列、日程执行器、需求队列、批量导出',
    recipe: ['Progress', 'StatusIndicator', 'ToastMessage', 'Table', 'ListRow'],
    rules: [
      '无独立界面的后台协调器只通过 Toast 和全局统计发声，不弹阻断浮层',
      '状态机、取消、失败重试和恢复规则遵循 MASTER 7.3',
    ],
    relatedMaster: 'MASTER 7.3',
  },
  {
    id: 'batch-exec-config-dialog',
    name: '批量执行配置弹窗',
    appliesTo: 'Agent 批量规划、画廊 SOP 批量、日程创建',
    recipe: ['Dialog', 'Fieldset', 'TextField', 'SelectField', 'Stepper', 'KeyValue', 'Alert', 'Button'],
    rules: [
      '提交前必须展示预估结果（将生成 N 张 / 消耗 M 个任务位）',
      '参数非法时主按钮禁用并就近提示原因',
      '提交后弹窗立即关闭，进度交给队列运行器汇报，不在弹窗内等待',
    ],
    relatedMaster: 'MASTER 6.6 / 7.3',
  },
  {
    id: 'dockable-sidebar',
    name: '可停靠侧栏',
    appliesTo: 'WorkspaceTabBar、WordLibrarySidebar',
    recipe: ['SplitPane', 'Panel', 'SearchField', 'NavList', 'ListRow', 'IconButton', 'Tooltip'],
    rules: [
      '停靠态与浮动态的视觉切换遵循 MASTER 4.6；宽度、停靠边和展开状态必须持久化',
      '侧栏内部结构：SearchField（可选）→ 主滚动区（NavList/ListRow）→ 固定操作区',
      '折叠后保留可发现的展开开关（IconButton + Tooltip），不完全消失',
    ],
    relatedMaster: 'MASTER 4.6',
  },
  {
    id: 'media-viewing-chain',
    name: '媒体查看链路',
    appliesTo: '所有出现图像缩略图的场景',
    recipe: ['Thumbnail', 'Popover', 'Dialog', 'Tabs'],
    rules: [
      '四级链路（Thumbnail → HoverImagePreview → Lightbox → DetailModal）职责与触发遵循 MASTER 6.6；不得跳级复用',
      'HoverImagePreview 基于 Popover，Lightbox 与 DetailModal 基于 Dialog（DetailModal 内用 Tabs）',
      '新场景若只需要两级（缩略图 + Lightbox），中间层直接省略，不做空壳',
    ],
    relatedMaster: 'MASTER 6.6',
  },
]

export interface PageCoverage {
  id: string
  workspace: string
  entry: string
  differences: string[]
  document: string
}

/** 各顶层工作区与全局规范的差异登记（对应 pages/ 目录）。 */
export const pageCoverage: PageCoverage[] = [
  {
    id: 'gallery',
    workspace: '画廊主页',
    entry: "appMode==='gallery'（默认）",
    differences: ['居中 max-w-7xl + 停靠浮动侧栏', '自实现鼠标框选', '无专属快捷键'],
    document: 'design-system/tangbao/pages/gallery.md',
  },
  {
    id: 'agent',
    workspace: 'Agent 工作台',
    entry: "appMode==='agent'",
    differences: ['会话侧栏可收起', '消息内嵌 AgentImageGrid', '无框选/专属快捷键'],
    document: 'design-system/tangbao/pages/agent.md',
  },
  {
    id: 'postprocess',
    workspace: '水印预设工作区',
    entry: "appMode==='postprocess'（顶栏第三个 tab，与素材库 / Agent 同级）",
    differences: ['与素材库/Agent 同级 tab', '图层拖拽编辑', 'Ctrl+Z 撤销'],
    document: 'design-system/tangbao/pages/postprocess.md',
  },
]

export const componentCategoryLabels: Record<ComponentCategory, string> = {
  foundation: '基础',
  layout: '布局',
  form: '表单',
  navigation: '导航',
  'data-display': '数据展示',
  feedback: '反馈',
  overlay: '浮层',
}
