import type { RequirementCatalog, RequirementSettings, RequirementUser } from './types'

export const REQUIREMENT_USERS: RequirementUser[] = [
  { id: 'user-optimizer', username: 'optimizer', displayName: '演示优化师', role: 'optimizer', dailyQuota: 2000 },
  { id: 'user-strategist', username: 'strategist', displayName: '演示策略师', role: 'strategist', dailyQuota: 2000 },
  { id: 'user-admin', username: 'admin', displayName: '系统管理员', role: 'admin', dailyQuota: 2000 },
]

export const DEFAULT_REQUIREMENT_SETTINGS: RequirementSettings = {
  maxImagesPerOrder: 500,
  defaultDailyQuota: 2000,
  defaultQuantity: 50,
  quantityShortcuts: [50, 100, 150, 200, 250],
  quantityStep: 10,
  generationConcurrency: 2,
  stableKnowledgeRatio: 0.8,
}

export function seedRequirementCatalog(): RequirementCatalog {
  return {
    products: [
      {
        id: 'product-xhs-app',
        name: '小红书 APP',
        category: '应用推广',
        summary: '生活方式内容与兴趣社区',
        facts: ['覆盖多元生活兴趣内容', '支持内容发现与经验分享'],
        audience: '关注生活方式、消费决策与兴趣内容的移动互联网用户',
        scenes: ['通勤浏览', '购物决策', '兴趣探索'],
        forbidden: ['虚构用户评价', '仿冒系统通知', '未经授权的品牌素材'],
        color: 'from-rose-500 to-red-500',
        published: true,
        version: 1,
      },
      {
        id: 'product-medical-insurance',
        name: '百万医疗险',
        category: '保险',
        summary: '医疗费用保障类保险产品',
        facts: ['具体保障范围以正式条款为准', '投保条件和等待期必须真实呈现'],
        audience: '关注家庭健康风险与医疗支出的成年用户',
        scenes: ['家庭健康规划', '医疗支出风险提示', '保障方案了解'],
        forbidden: ['保证理赔', '夸大疾病恐惧', '虚构保额或价格', '绝对化承诺'],
        color: 'from-sky-500 to-blue-600',
        published: true,
        version: 1,
      },
      {
        id: 'product-short-drama',
        name: '短剧图片',
        category: '内容娱乐',
        summary: '短剧内容推广与剧情吸引素材',
        facts: ['突出剧情冲突与人物关系', '保持角色和剧情信息一致'],
        audience: '偏好碎片化娱乐和强情节内容的用户',
        scenes: ['剧情悬念', '人物冲突', '情感转折'],
        forbidden: ['低俗擦边', '血腥暴力', '虚假播放按钮', '伪造平台界面'],
        color: 'from-violet-500 to-indigo-600',
        published: true,
        version: 1,
      },
    ],
    channels: [
      {
        id: 'channel-gdt',
        name: '广点通',
        summary: '腾讯广告信息流',
        ratios: ['16:9', '9:16'],
        requirements: ['信息层级清楚', '主体与核心卖点在安全区内', '避免仿冒腾讯产品界面'],
        forbidden: ['伪造微信或 QQ 界面', '红包中奖提示', '系统未读消息'],
        published: true,
        version: 1,
      },
      {
        id: 'channel-toutiao',
        name: '头条',
        summary: '头条信息流广告',
        ratios: ['16:9', '9:16'],
        requirements: ['首屏焦点明确', '文案简洁易读', '画面与落地页信息一致'],
        forbidden: ['伪新闻页面', '夸大功效', '诱导点击控件'],
        published: true,
        version: 1,
      },
      {
        id: 'channel-baidu',
        name: '百度',
        summary: '百度信息流广告',
        ratios: ['16:9', '9:16'],
        requirements: ['搜索意图相关', '产品信息明确', '避免模糊或不可读小字'],
        forbidden: ['虚构权威背书', '伪造搜索结果', '绝对化效果承诺'],
        published: true,
        version: 1,
      },
    ],
    materialTypes: [
      {
        id: 'type-pain',
        name: '痛点型',
        summary: '从真实问题切入，快速建立需求感知',
        mode: 'intelligent',
        strategy: '以真实、克制的用户问题为视觉入口，产品作为解决方案出现，避免焦虑夸大。',
        color: 'from-orange-400 to-amber-500',
        published: true,
        version: 1,
      },
      {
        id: 'type-scene',
        name: '场景型',
        summary: '用具体使用情境解释产品价值',
        mode: 'intelligent',
        strategy: '选择与目标人群高度相关的真实场景，通过人物、空间和产品关系表达价值。',
        color: 'from-emerald-400 to-teal-500',
        published: true,
        version: 1,
      },
      {
        id: 'type-benefit',
        name: '卖点型',
        summary: '集中呈现一个核心利益点',
        mode: 'intelligent',
        strategy: '每张图片只突出一个可验证核心卖点，建立清晰的信息层级和视觉焦点。',
        color: 'from-blue-400 to-cyan-500',
        published: true,
        version: 1,
      },
      {
        id: 'type-click',
        name: '诱导点击型',
        summary: '合规的兴趣钩子与信息悬念',
        mode: 'fixed',
        strategy: '使用合规兴趣引导。',
        fixedRules: [
          '使用疑问、局部揭示或信息差建立兴趣，但不得伪造交互控件。',
          '产品主体必须真实可识别，行动引导仅可使用“了解详情”等中性表达。',
          '禁止系统通知、未读消息、关闭按钮、中奖、红包、收益和虚假倒计时。',
        ],
        supportedRatios: ['16:9', '9:16'],
        color: 'from-fuchsia-500 to-pink-500',
        published: true,
        version: 1,
      },
      {
        id: 'type-promotion',
        name: '促销型',
        summary: '围绕真实活动信息组织促销画面',
        mode: 'fixed',
        strategy: '使用真实活动信息。',
        fixedRules: [
          '活动、价格、优惠和时间信息必须来自产品配置；缺失时不得自行编造。',
          '产品为主要视觉主体，优惠信息为第二层级，行动引导为第三层级。',
          '禁止虚假原价、夸张折扣、虚构限量、虚构倒计时和保证性承诺。',
        ],
        supportedRatios: ['16:9', '9:16'],
        color: 'from-red-500 to-orange-500',
        published: true,
        version: 1,
      },
    ],
  }
}
